### ISSUE TITLE
Update CMakeFiles to gnuradio 3.8.1?

### ISSUE THREAD

**Issue by johnzbesko** [tkuester/fixated#1]
My attempt to convert the CMakeFiles.txt to use gnuradio 3.8.1 did not work. Guess I'm too much of a noobie. I'm using Kubuntu 20.04, AMD64, though I intend to run this code on a RaspPi.

I'm hoping you see this issue and thank you for any reply.

**Comment by tkuester** [comment]
Per chance, did you mean to submit this to another repo? This one doens't
use CMake :)

**Comment by johnzbesko** [comment]
-------- Forwarded Message --------
From: John Zbesko <johnzbesko@alum.mit.edu>
Reply-To: johnzbesko@alum.mit.edu
To: Tim K <notifications@github.com>
Subject: Re: [tkuester/fixated] Update CMakeFiles to gnuradio 3.8.1? 
(#1)
Date: Sat, 31 Oct 2020 14:37:49 -0500

Thank you for your reply. I added an issue to gr-lacrosse and explained
a little more about what I'm trying to accomplish.

JZ
